# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\natha\OneDrive\Desktop\CS\NEA\questionwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
##    def __init__(self,question,answer1,answer2,answer3,answer4):
##        self.question = question
##        self.answer1 = answer1
##        self.answer2 = answer2
##        self.answer3 = answer3
##        self.answer4 = answer4
    def setupUi(self, MainWindow,question,answer1,answer2,answer3,answer4):
        MainWindow.setObjectName("MainWin")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.question = QtWidgets.QLabel(self.centralwidget)
        self.question.setGeometry(QtCore.QRect(170, 230, 460, 90))
        self.question.setAutoFillBackground(True)
        self.question.setFrameShape(QtWidgets.QFrame.Box)
        self.question.setFrameShadow(QtWidgets.QFrame.Plain)
        self.question.setLineWidth(1)
        self.question.setObjectName("question")
        self.ans1 = QtWidgets.QPushButton(self.centralwidget)
        self.ans1.setGeometry(QtCore.QRect(170, 350, 220, 50))
        self.ans1.setObjectName("ans1")
        self.ans2 = QtWidgets.QPushButton(self.centralwidget)
        self.ans2.setGeometry(QtCore.QRect(410, 350, 220, 50))
        self.ans2.setObjectName("ans2")
        self.ans3 = QtWidgets.QPushButton(self.centralwidget)
        self.ans3.setGeometry(QtCore.QRect(170, 420, 220, 50))
        self.ans3.setObjectName("ans3")
        self.ans4 = QtWidgets.QPushButton(self.centralwidget)
        self.ans4.setGeometry(QtCore.QRect(410, 420, 220, 50))
        self.ans4.setObjectName("ans4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow,question,answer1,answer2,answer3,answer4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow,question,answer1,answer2,answer3,answer4):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWin", "MainWin"))
        self.question.setText(_translate("MainWindow", question))
        self.ans3.setText(_translate("MainWindow", answer3))
        self.ans4.setText(_translate("MainWindow", answer4))
        self.ans1.setText(_translate("MainWindow", answer1))
        self.ans2.setText(_translate("MainWindow", answer2))


def runqueswin(question,answer1,answer2,answer3,answer4):
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow,question,answer1,answer2,answer3,answer4)
    MainWindow.show()
    sys.exit(app.exec_())
